# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 database configuration
spring.datasource.url=jdbc:h2:mem:ecomdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.username=sa
spring.datasource.password=k6oS3aLoR4tbL3wsgRfEXRIdb6GzSulMcg6adLV6TOQ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.security.user.name=admin
spring.security.user.password=admin

